export const el = {
    userList: document.getElementById("userList")! as HTMLSelectElement,
    removeUser: document.getElementById("removeUser")!,
    userName: document.getElementById("userName")! as HTMLInputElement,
    userEmail: document.getElementById("userEmail")! as HTMLInputElement,
    addUser: document.getElementById("addUser")!,
    categoryList: document.getElementById("categoryList")!,
    categoryName: document.getElementById("categoryName")! as HTMLInputElement,
    addCategory: document.getElementById("addCategory")!,
    categoryTitle: document.getElementById("categoryTitle")!,
    todos: document.getElementById("todos")!,
    todoTitle: document.getElementById("todoTitle")! as HTMLInputElement,
    addTodo: document.getElementById("addTodo")!,
    todoList: document.getElementById("todoList")!,
    doneList: document.getElementById("doneList")!,
};